<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;
    protected $table = "countries";
    protected $guarded = [];
    protected $hidden = ['created_at', 'updated_at'];

    public static $countries = [
        [
            "id" => 1,
            "name" => "Afghanistan",
            "currency" => "AFN",
            "phone" => 93,
            "code" => "AF",
            "number" => 4,
        ],
        [
            "id" => 2,
            "name" => "South Africa",
            "currency" => "ZAR",
            "phone" => 27,
            "code" => "ZA",
            "number" => 710,
        ],
        [
            "id" => 3,
            "name" => "Albania",
            "currency" => "ALL",
            "phone" => 355,
            "code" => "AL",
            "number" => 8,
        ],
        [
            "id" => 4,
            "name" => "Germany",
            "currency" => "EUR",
            "phone" => 49,
            "code" => "DE",
            "number" => 276,
        ],
        [
            "id" => 5,
            "name" => "Andorra",
            "currency" => "EUR",
            "phone" => 376,

            "code" => "AD",
            "number" => 20,
        ],
        [
            "id" => 6,
            "name" => "Angola",
            "currency" => "AOA",
            "phone" => 244,
            "code" => "AO",
            "number" => 24,
        ],
        [
            "id" => 7,
            "name" => "Anguilla",
            "currency" => "XCD",
            "phone" => 1264,
            "code" => "AI",
            "number" => 660,
        ],
        [
            "id" => 8,
            "name" => "Antarctica",
            "currency" => "AAD",
            "phone" => 672,
            "code" => "AQ",
            "number" => 10,
        ],
        [
            "id" => 9,
            "name" => "Antigua and Barbuda",
            "currency" => "XCD",
            "phone" => 1268,
            "code" => "AG",
            "number" => 28,
        ],
        [
            "id" => 11,
            "name" => "Saudi Arabia",
            "currency" => "SAR",
            "phone" => 966,
            "code" => "SA",
            "number" => 682,
        ],
        [
            "id" => 12,
            "name" => "Algeria",
            "currency" => "DZD",
            "phone" => 213,
            "code" => "DZ",
            "number" => 12,
        ],
        [
            "id" => 13,
            "name" => "Argentina",
            "currency" => "ARS",
            "phone" => 54,
            "code" => "AR",
            "number" => 32,
        ],
        [
            "id" => 14,
            "name" => "Armenia",
            "currency" => "AMD",
            "phone" => 374,
            "code" => "AM",
            "number" => 51,
        ],
        [
            "id" => 15,
            "name" => "Aruba",
            "currency" => "AWG",
            "phone" => 297,
            "code" => "AW",
            "number" => 533,
        ],
        [
            "id" => 16,
            "name" => "Australia",
            "currency" => "AUD",
            "phone" => 61,
            "code" => "AU",
            "number" => 36,
        ],
        [
            "id" => 17,
            "name" => "Austria",
            "currency" => "EUR",
            "phone" => 43,
            "code" => "AT",
            "number" => 40,
        ],
        [
            "id" => 18,
            "name" => "Azerbaijan",
            "currency" => "AZN",
            "phone" => 994,
            "code" => "AZ",
            "number" => 31,
        ],
        [
            "id" => 19,
            "name" => "Bahamas, The",
            "currency" => "BSD",
            "phone" => 1242,
            "code" => "BS",
            "number" => 44,
        ],
        [
            "id" => 20,
            "name" => "Bahrain",
            "currency" => "BHD",
            "phone" => 973,
            "code" => "BH",
            "number" => 48,
        ],
        [
            "id" => 21,
            "name" => "Bangladesh",
            "currency" => "BDT",
            "phone" => 880,
            "code" => "BD",
            "number" => 50,
        ],
        [
            "id" => 22,
            "name" => "Barbados",
            "currency" => "BBD",
            "phone" => 1246,
            "code" => "BB",
            "number" => 52,
        ],
        [
            "id" => 23,
            "name" => "Belgium",
            "currency" => "EUR",
            "phone" => 32,
            "code" => "BE",
            "number" => 56,
        ],
        [
            "id" => 24,
            "name" => "Belize",
            "currency" => "BZD",
            "phone" => 501,
            "code" => "BZ",
            "number" => 84,
        ],
        [
            "id" => 25,
            "name" => "Benin",
            "currency" => "XOF",
            "phone" => 229,
            "code" => "BJ",
            "number" => 204,
        ],
        [
            "id" => 26,
            "name" => "Bermuda",
            "currency" => "BMD",
            "phone" => 1441,
            "code" => "BM",
            "number" => 60,
        ],
        [
            "id" => 27,
            "name" => "Belarus",
            "currency" => "BYN",
            "phone" => 375,
            "code" => "BY",
            "number" => 112,
        ],
        [
            "id" => 28,
            "name" => "Bolivia",
            "currency" => "BOB",
            "phone" => 591,
            "code" => "BO",
            "number" => 68,
        ],
        [
            "id" => 29,
            "name" => "Bosnia and Herzegovina",
            "currency" => "BAM",
            "phone" => 387,
            "code" => "BA",
            "number" => 70,
        ],
        [
            "id" => 30,
            "name" => "Botswana",
            "currency" => "BWP",
            "phone" => 267,
            "code" => "BW",
            "number" => 72,
        ],
        [
            "id" => 31,
            "name" => "Brazil",
            "currency" => "BRL",
            "phone" => 55,
            "code" => "BR",
            "number" => 76,
        ],
        [
            "id" => 32,
            "name" => "Brunei",
            "currency" => "BND",
            "phone" => 673,

            "code" => "BN",
            "number" => 96,
        ],
        [
            "id" => 33,
            "name" => "Bulgaria",
            "currency" => "BGN",
            "phone" => 359,
            "code" => "BG",
            "number" => 100,
        ],
        [
            "id" => 34,
            "name" => "Burkina Faso",
            "currency" => "XOF",
            "phone" => 226,
            "code" => "BF",
            "number" => 854,
        ],
        [
            "id" => 35,
            "name" => "Burundi",
            "currency" => "BIF",
            "phone" => 257,
            "code" => "BI",
            "number" => 108,
        ],
        [
            "id" => 36,
            "name" => "Bhutan",
            "currency" => "BTN",
            "phone" => 975,
            "code" => "BT",
            "number" => 64,
        ],
        [
            "id" => 37,
            "name" => "Cabo Verde",
            "currency" => "CVE",
            "phone" => 238,
            "code" => "CV",
            "number" => 132,
        ],
        [
            "id" => 38,
            "name" => "Cameroon",
            "currency" => "XAF",
            "phone" => 237,
            "code" => "CM",
            "number" => 120,
        ],
        [
            "id" => 39,
            "name" => "Cambodia",
            "currency" => "KHR",
            "phone" => 855,
            "code" => "KH",
            "number" => 116,
        ],
        [
            "id" => 40,
            "name" => "Canada",
            "currency" => "CAD",
            "phone" => 1,
            "code" => "CA",
            "number" => 124,
        ],
        [
            "id" => 41,
            "name" => "Qatar",
            "currency" => "QAR",
            "phone" => 974,
            "code" => "QA",
            "number" => 634,
        ],
        [
            "id" => 42,
            "name" => "Kazakhstan",
            "currency" => "KZT",
            "phone" => 7,
            "code" => "KZ",
            "number" => 398,
        ],
        [
            "id" => 43,
            "name" => "Chad",
            "currency" => "XAF",
            "phone" => 235,
            "code" => "TD",
            "number" => 148,
        ],
        [
            "id" => 44,
            "name" => "Chile",
            "currency" => "CLP",
            "phone" => 56,
            "code" => "CL",
            "number" => 152,
        ],
        [
            "id" => 45,
            "name" => "China",
            "currency" => "CNY",
            "phone" => 86,
            "code" => "CN",
            "number" => 156,
        ],
        [
            "id" => 46,
            "name" => "Cyprus",
            "currency" => "EUR",
            "phone" => 357,
            "code" => "CY",
            "number" => 196,
        ],
        [
            "id" => 47,
            "name" => "Singapore",
            "currency" => "SGD",
            "phone" => 65,
            "code" => "SG",
            "number" => 702,
        ],
        [
            "id" => 48,
            "name" => "Colombia",
            "currency" => "COP",
            "phone" => 57,
            "code" => "CO",
            "number" => 170,
        ],
        [
            "id" => 49,
            "name" => "Comoros",
            "currency" => "KMF",
            "phone" => 269,
            "code" => "KM",
            "number" => 174,
        ],
        [
            "id" => 50,
            "name" => "Congo",
            "currency" => "XAF",
            "phone" => 242,
            "code" => "CG",
            "number" => 178,
        ],
        [
            "id" => 51,
            "name" => "North Korea",
            "currency" => "KPW",
            "phone" => 850,
            "code" => "KP",
            "number" => 408,
        ],
        [
            "id" => 52,
            "name" => "Korea",
            "currency" => "KRW",
            "phone" => 82,
            "code" => "KR",
            "number" => 410,
        ],
        [
            "id" => 53,
            "name" => "Côte d'Ivoire",
            "currency" => "XOF",
            "phone" => 225,
            "code" => "CI",
            "number" => 384,
        ],
        [
            "id" => 54,
            "name" => "Costa Rica",
            "currency" => "CRC",
            "phone" => 506,
            "code" => "CR",
            "number" => 188,
        ],
        [
            "id" => 55,
            "name" => "Croatia",
            "currency" => "HRK",
            "phone" => 385,
            "code" => "HR",
            "number" => 191,
        ],
        [
            "id" => 56,
            "name" => "Cuba",
            "currency" => "CUP",
            "phone" => 53,
            "code" => "CU",
            "number" => 192,
        ],
        [
            "id" => 57,
            "name" => "Curaçao",
            "currency" => "ANG",
            "phone" => 599,
            "code" => "CW",
            "number" => 531,
        ],
        [
            "id" => 58,
            "name" => "Denmark",
            "currency" => "DKK",
            "phone" => 45,
            "code" => "DK",
            "number" => 208,
        ],
        [
            "id" => 59,
            "name" => "Djibouti",
            "currency" => "DJF",
            "phone" => 253,
            "code" => "DJ",
            "number" => 262,
        ],
        [
            "id" => 60,
            "name" => "Dominica",
            "currency" => "XCD",
            "phone" => 1767,
            "code" => "DM",
            "number" => 212,
        ],
        [
            "id" => 61,
            "name" => "Egypt",
            "currency" => "EGP",
            "phone" => 20,
            "code" => "EG",
            "number" => 818,
        ],
        [
            "id" => 62,
            "name" => "El Salvador",
            "currency" => "USD",
            "phone" => 503,
            "code" => "SV",
            "number" => 222,
        ],
        [
            "id" => 63,
            "name" => "United Arab Emirates",
            "currency" => "AED",
            "phone" => 971,
            "code" => "AE",
            "number" => 784,
        ],
        [
            "id" => 64,
            "name" => "Ecuador",
            "currency" => "USD",
            "phone" => 593,
            "code" => "EC",
            "number" => 218,
        ],
        [
            "id" => 65,
            "name" => "Eritrea",
            "currency" => "ERN",
            "phone" => 291,
            "code" => "ER",
            "number" => 232,
        ],
        [
            "id" => 66,
            "name" => "Slovakia",
            "currency" => "EUR",
            "phone" => 421,
            "code" => "SK",
            "number" => 703,
        ],
        [
            "id" => 67,
            "name" => "Slovenia",
            "currency" => "EUR",
            "phone" => 386,
            "code" => "SI",
            "number" => 705,
        ],
        [
            "id" => 68,
            "name" => "Spain",
            "currency" => "EUR",
            "phone" => 34,
            "code" => "ES",
            "number" => 724,
        ],
        [
            "id" => 69,
            "name" => "United States",
            "currency" => "USD",
            "phone" => 1,
            "code" => "US",
            "number" => 840,
        ],
        [
            "id" => 70,
            "name" => "Estonia",
            "currency" => "EUR",
            "phone" => 372,
            "code" => "EE",
            "number" => 233,
        ],
        [
            "id" => 71,
            "name" => "Ethiopia",
            "currency" => "ETB",
            "phone" => 251,
            "code" => "ET",
            "number" => 231,
        ],
        [
            "id" => 72,
            "name" => "Fiji Islands",
            "currency" => "FJD",
            "phone" => 679,
            "code" => "FJ",
            "number" => 242,
        ],
        [
            "id" => 73,
            "name" => "Philippines",
            "currency" => "PHP",
            "phone" => 63,
            "code" => "PH",
            "number" => 608,
        ],
        [
            "id" => 74,
            "name" => "Finland",
            "currency" => "EUR",
            "phone" => 358,
            "code" => "FI",
            "number" => 246,
        ],
        [
            "id" => 75,
            "name" => "France",
            "currency" => "EUR",
            "phone" => 33,
            "code" => "FR",
            "number" => 250,
        ],
        [
            "id" => 76,
            "name" => "Gabon",
            "currency" => "XAF",
            "phone" => 241,
            "code" => "GA",
            "number" => 266,
        ],
        [
            "id" => 77,
            "name" => "Gambia, The",
            "currency" => "GMD",
            "phone" => 220,
            "code" => "GM",
            "number" => 270,
        ],
        [
            "id" => 78,
            "name" => "Ghana",
            "currency" => "GHS",
            "phone" => 233,
            "code" => "GH",
            "number" => 288,
        ],
        [
            "id" => 79,
            "name" => "Georgia",
            "currency" => "GEL",
            "phone" => 995,
            "code" => "GE",
            "number" => 268,
        ],
        [
            "id" => 80,
            "name" => "Gibraltar",
            "currency" => "GIP",
            "phone" => 350,
            "code" => "GI",
            "number" => 292,
        ],
        [
            "id" => 81,
            "name" => "Grenada",
            "currency" => "XCD",
            "phone" => 1473,
            "code" => "GD",
            "number" => 308,
        ],
        [
            "id" => 82,
            "name" => "Greece",
            "currency" => "EUR",
            "phone" => 30,
            "code" => "GR",
            "number" => 300,
        ],
        [
            "id" => 83,
            "name" => "Greenland",
            "currency" => "DKK",
            "phone" => 299,
            "code" => "GL",
            "number" => 304,
        ],
        [
            "id" => 84,
            "name" => "Guadeloupe",
            "currency" => "EUR",
            "phone" => 590,
            "code" => "GP",
            "number" => 312,
        ],
        [
            "id" => 85,
            "name" => "Guam",
            "currency" => "USD",
            "phone" => 1671,
            "code" => "GU",
            "number" => 316,
        ],
        [
            "id" => 86,
            "name" => "Guatemala",
            "currency" => "GTQ",
            "phone" => 502,
            "code" => "GT",
            "number" => 320,
        ],
        [
            "id" => 87,
            "name" => "Guernsey",
            "currency" => "GBP",
            "phone" => 44,
            "code" => "GG",
            "number" => 831,
        ],
        [
            "id" => 88,
            "name" => "Guyana",
            "currency" => "GYD",
            "phone" => 592,
            "code" => "GY",
            "number" => 328,
        ],
        [
            "id" => 89,
            "name" => "French Guiana",
            "currency" => "EUR",
            "phone" => 594,
            "code" => "GF",
            "number" => 254,
        ],
        [
            "id" => 90,
            "name" => "Guinea",
            "currency" => "GNF",
            "phone" => 224,
            "code" => "GN",
            "number" => 324,
        ],
        [
            "id" => 91,
            "name" => "Equatorial Guinea",
            "currency" => "XAF",
            "phone" => 240,
            "code" => "GQ",
            "number" => 226,
        ],
        [
            "id" => 92,
            "name" => "Guinea-Bissau",
            "currency" => "XOF",
            "phone" => 245,
            "code" => "GW",
            "number" => 624,
        ],
        [
            "id" => 93,
            "name" => "Haiti",
            "currency" => "HTG",
            "phone" => 509,
            "code" => "HT",
            "number" => 332,
        ],
        [
            "id" => 94,
            "name" => "Netherlands",
            "currency" => "EUR",
            "phone" => 31,
            "code" => "NL",
            "number" => 528,
        ],
        [
            "id" => 95,
            "name" => "Honduras",
            "currency" => "HNL",
            "phone" => 504,
            "code" => "HN",
            "number" => 340,
        ],
        [
            "id" => 96,
            "name" => "Hong Kong SAR",
            "currency" => "HKD",
            "phone" => 852,
            "code" => "HK",
            "number" => 344,
        ],
        [
            "id" => 97,
            "name" => "Hungary",
            "currency" => "HUF",
            "phone" => 36,
            "code" => "HU",
            "number" => 348,
        ],
        [
            "id" => 98,
            "name" => "Yemen",
            "currency" => "YER",
            "phone" => 967,
            "code" => "YE",
            "number" => 887,
        ],
        [
            "id" => 99,
            "name" => "Bouvet Island",
            "currency" => "NOK",
            "phone" => 55,
            "code" => "BV",
            "number" => 74,
        ],
        [
            "id" => 100,
            "name" => "Reunion",
            "currency" => "EUR",
            "phone" => 262,
            "code" => "RE",
            "number" => 638,
        ],
        [
            "id" => 101,
            "name" => "Man, Isle of",
            "currency" => "GBP",
            "phone" => 44,
            "code" => "IM",
            "number" => 833,
        ],
        [
            "id" => 102,
            "name" => "Saint Martin (French part)",
            "currency" => "EUR",
            "phone" => 590,
            "code" => "MF",
            "number" => 663,
        ],
        [
            "id" => 103,
            "name" => "Heard Island and McDonald Islands",
            "currency" => "AUD",
            "phone" => 0,
            "code" => "HM",
            "number" => 334,
        ],
        [
            "id" => 104,
            "name" => "Christmas Island",
            "currency" => "AUD",
            "phone" => 61,

            "code" => "CX",
            "number" => 162,
        ],
        [
            "id" => 105,
            "name" => "Norfolk Island",
            "currency" => "AUD",
            "phone" => 672,
            "code" => "NF",
            "number" => 574,
        ],
        [
            "id" => 106,
            "name" => "Aland Islands",
            "currency" => "EUR",
            "phone" => 358,
            "code" => "AX",
            "number" => 248,
        ],
        [
            "id" => 107,
            "name" => "Cayman Islands",
            "currency" => "KYD",
            "phone" => 1345,
            "code" => "KY",
            "number" => 136,
        ],
        [
            "id" => 108,
            "name" => "Cocos (Keeling) Islands",
            "currency" => "AUD",
            "phone" => 672,
            "code" => "CC",
            "number" => 166,
        ],
        [
            "id" => 109,
            "name" => "Cook Islands",
            "currency" => "NZD",
            "phone" => 682,
            "code" => "CK",
            "number" => 184,
        ],
        [
            "id" => 110,
            "name" => "Falkland Islands (Islas Malvinas)",
            "currency" => "FKP",
            "phone" => 500,
            "code" => "FK",
            "number" => 238,
        ],
        [
            "id" => 111,
            "name" => "Faroe Islands",
            "currency" => "DKK",
            "phone" => 298,
            "code" => "FO",
            "number" => 234,
        ],
        [
            "id" => 112,
            "name" => "South Georgia and the South Sandwich Islands",
            "currency" => "GBP",
            "phone" => 500,
            "code" => "GS",
            "number" => 239,
        ],
        [
            "id" => 113,
            "name" => "Northern Mariana Islands",
            "currency" => "USD",
            "phone" => 1670,
            "code" => "MP",
            "number" => 580,
        ],
        [
            "id" => 114,
            "name" => "Marshall Islands",
            "currency" => "USD",
            "phone" => 692,
            "code" => "MH",
            "number" => 584,
        ],
        [
            "id" => 115,
            "name" => "U.S. Minor Outlying Islands",
            "currency" => "USD",
            "phone" => 246,
            "code" => "UM",
            "number" => 581,
        ],
        [
            "id" => 116,
            "name" => "Pitcairn Islands",
            "currency" => "NZD",
            "phone" => 64,
            "code" => "PN",
            "number" => 612,
        ],
        [
            "id" => 117,
            "name" => "Solomon Islands",
            "currency" => "SBD",
            "phone" => 677,
            "code" => "SB",
            "number" => 90,
        ],
        [
            "id" => 118,
            "name" => "Turks and Caicos Islands",
            "currency" => "USD",
            "phone" => 1649,
            "code" => "TC",
            "number" => 796,
        ],
        [
            "id" => 119,
            "name" => "Virgin Islands, U.S.",
            "currency" => "USD",
            "phone" => 1340,

            "code" => "VI",
            "number" => 850,
        ],
        [
            "id" => 120,
            "name" => "Virgin Islands, British",
            "currency" => "USD",
            "phone" => 1284,
            "code" => "VG",
            "number" => 92,
        ],
        [
            "id" => 121,
            "name" => "India",
            "currency" => "INR",
            "phone" => 91,
            "code" => "IN",
            "number" => 356,
        ],
        [
            "id" => 122,
            "name" => "Indonesia",
            "currency" => "IDR",
            "phone" => 62,
            "code" => "ID",
            "number" => 360,
        ],
        [
            "id" => 123,
            "name" => "Iran",
            "currency" => "IRR",
            "phone" => 98,
            "code" => "IR",
            "number" => 364,
        ],
        [
            "id" => 124,
            "name" => "Iraq",
            "currency" => "IQD",
            "phone" => 964,
            "code" => "IQ",
            "number" => 368,
        ],
        [
            "id" => 125,
            "name" => "Ireland",
            "currency" => "EUR",
            "phone" => 353,
            "code" => "IE",
            "number" => 372,
        ],
        [
            "id" => 126,
            "name" => "Iceland",
            "currency" => "ISK",
            "phone" => 354,
            "code" => "IS",
            "number" => 352,
        ],
        [
            "id" => 127,
            "name" => "Israel",
            "currency" => "ILS",
            "phone" => 972,
            "code" => "IL",
            "number" => 376,
        ],
        [
            "id" => 128,
            "name" => "Italy",
            "currency" => "EUR",
            "phone" => 39,
            "code" => "IT",
            "number" => 380,
        ],
        [
            "id" => 129,
            "name" => "Jamaica",
            "currency" => "JMD",
            "phone" => 1876,
            "code" => "JM",
            "number" => 388,
        ],
        [
            "id" => 130,
            "name" => "Japan",
            "currency" => "JPY",
            "phone" => 81,
            "code" => "JP",
            "number" => 392,
        ],
        [
            "id" => 131,
            "name" => "Jersey",
            "currency" => "GBP",
            "phone" => 44,
            "code" => "JE",
            "number" => 832,
        ],
        [
            "id" => 132,
            "name" => "Jordan",
            "currency" => "JOD",
            "phone" => 962,
            "code" => "JO",
            "number" => 400,
        ],
        [
            "id" => 133,
            "name" => "Kiribati",
            "currency" => "AUD",
            "phone" => 686,
            "code" => "KI",
            "number" => 296,
        ],
        [
            "id" => 134,
            "name" => "Kosovo",
            "currency" => "EUR",
            "phone" => 383,
            "code" => "XK",
            "number" => 926,
        ],
        [
            "id" => 135,
            "name" => "Kuwait",
            "currency" => "KWD",
            "phone" => 965,
            "code" => "KW",
            "number" => 414,
        ],
        [
            "id" => 136,
            "name" => "Laos",
            "currency" => "LAK",
            "phone" => 856,
            "code" => "LA",
            "number" => 418,
        ],
        [
            "id" => 137,
            "name" => "Lesotho",
            "currency" => "LSL",
            "phone" => 266,
            "code" => "LS",
            "number" => 426,
        ],
        [
            "id" => 138,
            "name" => "Latvia",
            "currency" => "EUR",
            "phone" => 371,
            "code" => "LV",
            "number" => 428,
        ],
        [
            "id" => 139,
            "name" => "Lebanon",
            "currency" => "LBP",
            "phone" => 961,
            "code" => "LB",
            "number" => 422,
        ],
        [
            "id" => 140,
            "name" => "Liberia",
            "currency" => "LRD",
            "phone" => 231,
            "code" => "LR",
            "number" => 430,
        ],
        [
            "id" => 141,
            "name" => "Libya",
            "currency" => "LYD",
            "phone" => 218,
            "code" => "LY",
            "number" => 434,
        ],
        [
            "id" => 142,
            "name" => "Liechtenstein",
            "currency" => "CHF",
            "phone" => 423,
            "code" => "LI",
            "number" => 438,
        ],
        [
            "id" => 143,
            "name" => "Lithuania",
            "currency" => "EUR",
            "phone" => 370,
            "code" => "LT",
            "number" => 440,
        ],
        [
            "id" => 144,
            "name" => "Luxembourg",
            "currency" => "EUR",
            "phone" => 352,
            "code" => "LU",
            "number" => 442,
        ],
        [
            "id" => 145,
            "name" => "Macao SAR",
            "currency" => "MOP",
            "phone" => 853,
            "code" => "MO",
            "number" => 446,
        ],
        [
            "id" => 146,
            "name" => "Macedonia, Former Yugoslav Republic of",
            "currency" => "MKD",
            "phone" => 389,
            "code" => "MK",
            "number" => 807,
        ],
        [
            "id" => 147,
            "name" => "Madagascar",
            "currency" => "MGA",
            "phone" => 261,
            "code" => "MG",
            "number" => 450,
        ],
        [
            "id" => 148,
            "name" => "Malaysia",
            "currency" => "MYR",
            "phone" => 60,
            "code" => "MY",
            "number" => 458,
        ],
        [
            "id" => 149,
            "name" => "Malawi",
            "currency" => "MWK",
            "phone" => 265,
            "code" => "MW",
            "number" => 454,
        ],
        [
            "id" => 150,
            "name" => "Maldives",
            "currency" => "MVR",
            "phone" => 960,
            "code" => "MV",
            "number" => 462,
        ],
        [
            "id" => 151,
            "name" => "Mali",
            "currency" => "XOF",
            "phone" => 223,
            "code" => "ML",
            "number" => 466,
        ],
        [
            "id" => 152,
            "name" => "Malta",
            "currency" => "EUR",
            "phone" => 356,
            "code" => "MT",
            "number" => 470,
        ],
        [
            "id" => 153,
            "name" => "Morocco",
            "currency" => "MAD",
            "phone" => 212,
            "code" => "MA",
            "number" => 504,
        ],
        [
            "id" => 154,
            "name" => "Martinique",
            "currency" => "EUR",
            "phone" => 596,
            "code" => "MQ",
            "number" => 474,
        ],
        [
            "id" => 155,
            "name" => "Mauritius",
            "currency" => "MUR",
            "phone" => 230,
            "code" => "MU",
            "number" => 480,
        ],
        [
            "id" => 156,
            "name" => "Mauritania",
            "currency" => "MRO",
            "phone" => 222,
            "code" => "MR",
            "number" => 478,
        ],
        [
            "id" => 157,
            "name" => "Mayotte",
            "currency" => "EUR",
            "phone" => 269,
            "code" => "YT",
            "number" => 175,
        ],
        [
            "id" => 158,
            "name" => "Mexico",
            "currency" => "MXN",
            "phone" => 52,
            "code" => "MX",
            "number" => 484,
        ],
        [
            "id" => 159,
            "name" => "Micronesia",
            "currency" => "USD",
            "phone" => 691,
            "code" => "FM",
            "number" => 583,
        ],
        [
            "id" => 160,
            "name" => "Mozambique",
            "currency" => "MZN",
            "phone" => 258,
            "code" => "MZ",
            "number" => 508,
        ],
        [
            "id" => 161,
            "name" => "Moldova",
            "currency" => "MDL",
            "phone" => 373,
            "code" => "MD",
            "number" => 498,
        ],
        [
            "id" => 162,
            "name" => "Monaco",
            "currency" => "EUR",
            "phone" => 377,
            "code" => "MC",
            "number" => 492,
        ],
        [
            "id" => 163,
            "name" => "Mongolia",
            "currency" => "MNT",
            "phone" => 976,
            "code" => "MN",
            "number" => 496,
        ],
        [
            "id" => 164,
            "name" => "Montenegro",
            "currency" => "EUR",
            "phone" => 382,
            "code" => "ME",
            "number" => 499,
        ],
        [
            "id" => 165,
            "name" => "Montserrat",
            "currency" => "XCD",
            "phone" => 1664,
            "code" => "MS",
            "number" => 500,
        ],
        [
            "id" => 166,
            "name" => "Myanmar",
            "currency" => "MMK",
            "phone" => 95,
            "code" => "MM",
            "number" => 104,
        ],
        [
            "id" => 167,
            "name" => "Namibia",
            "currency" => "NAD",
            "phone" => 264,
            "code" => "NA",
            "number" => 516,
        ],
        [
            "id" => 168,
            "name" => "Nauru",
            "currency" => "AUD",
            "phone" => 674,
            "code" => "NR",
            "number" => 520,
        ],
        [
            "id" => 169,
            "name" => "Nepal",
            "currency" => "NPR",
            "phone" => 977,
            "code" => "NP",
            "number" => 524,
        ],
        [
            "id" => 170,
            "name" => "Nicaragua",
            "currency" => "NIO",
            "phone" => 505,
            "code" => "NI",
            "number" => 558,
        ],
        [
            "id" => 171,
            "name" => "Niger",
            "currency" => "XOF",
            "phone" => 227,
            "code" => "NE",
            "number" => 562,
        ],
        [
            "id" => 172,
            "name" => "Nigeria",
            "currency" => "NGN",
            "phone" => 234,
            "code" => "NG",
            "number" => 566,
        ],
        [
            "id" => 173,
            "name" => "Niue",
            "currency" => "NZD",
            "phone" => 683,
            "code" => "NU",
            "number" => 570,
        ],
        [
            "id" => 174,
            "name" => "Norway",
            "currency" => "NOK",
            "phone" => 47,
            "code" => "NO",
            "number" => 578,
        ],
        [
            "id" => 175,
            "name" => "New Caledonia",
            "currency" => "XPF",
            "phone" => 687,
            "code" => "NC",
            "number" => 540,
        ],
        [
            "id" => 176,
            "name" => "New Zealand",
            "currency" => "NZD",
            "phone" => 64,
            "code" => "NZ",
            "number" => 554,
        ],
        [
            "id" => 177,
            "name" => "Oman",
            "currency" => "OMR",
            "phone" => 968,
            "code" => "OM",
            "number" => 512,
        ],
        [
            "id" => 178,
            "name" => "Palau",
            "currency" => "USD",
            "phone" => 680,
            "code" => "PW",
            "number" => 585,
        ],
        [
            "id" => 179,
            "name" => "Panama",
            "currency" => "PAB",
            "phone" => 507,
            "code" => "PA",
            "number" => 591,
        ],
        [
            "id" => 180,
            "name" => "Papua New Guinea",
            "currency" => "PGK",
            "phone" => 675,
            "code" => "PG",
            "number" => 598,
        ],
        [
            "id" => 181,
            "name" => "Pakistan",
            "currency" => "PKR",
            "phone" => 92,
            "code" => "PK",
            "number" => 586,
        ],
        [
            "id" => 182,
            "name" => "Paraguay",
            "currency" => "PYG",
            "phone" => 595,
            "code" => "PY",
            "number" => 600,
        ],
        [
            "id" => 183,
            "name" => "Peru",
            "currency" => "PEN",
            "phone" => 51,
            "code" => "PE",
            "number" => 604,
        ],
        [
            "id" => 184,
            "name" => "French Polynesia",
            "currency" => "XPF",
            "phone" => 689,
            "code" => "PF",
            "number" => 258,
        ],
        [
            "id" => 185,
            "name" => "Poland",
            "currency" => "PLN",
            "phone" => 48,
            "code" => "PL",
            "number" => 616,
        ],
        [
            "id" => 186,
            "name" => "Puerto Rico",
            "currency" => "USD",
            "phone" => 1787,
            "code" => "PR",
            "number" => 630,
        ],
        [
            "id" => 187,
            "name" => "Portugal",
            "currency" => "EUR",
            "phone" => 351,
            "code" => "PT",
            "number" => 620,
        ],
        [
            "id" => 188,
            "name" => "Kenya",
            "currency" => "KES",
            "phone" => 254,
            "code" => "KE",
            "number" => 404,
        ],
        [
            "id" => 189,
            "name" => "Kyrgyzstan",
            "currency" => "KGS",
            "phone" => 996,
            "code" => "KG",
            "number" => 417,
        ],
        [
            "id" => 190,
            "name" => "United Kingdom",
            "currency" => "GBP",
            "phone" => 44,
            "code" => "GB",
            "number" => 826,
        ],
        [
            "id" => 191,
            "name" => "Central African Republic",
            "currency" => "XAF",
            "phone" => 236,
            "code" => "CF",
            "number" => 140,
        ],
        [
            "id" => 192,
            "name" => "Congo (DRC)",
            "currency" => "CDF",
            "phone" => 242,
            "code" => "CD",
            "number" => 180,
        ],
        [
            "id" => 193,
            "name" => "Dominican Republic",
            "currency" => "DOP",
            "phone" => 1809,
            "code" => "DO",
            "number" => 214,
        ],
        [
            "id" => 194,
            "name" => "Czech Republic",
            "currency" => "CZK",
            "phone" => 420,
            "code" => "CZ",
            "number" => 203,
        ],
        [
            "id" => 195,
            "name" => "Romania",
            "currency" => "RON",
            "phone" => 40,
            "code" => "RO",
            "number" => 642,
        ],
        [
            "id" => 196,
            "name" => "Rwanda",
            "currency" => "RWF",
            "phone" => 250,
            "code" => "RW",
            "number" => 646,
        ],
        [
            "id" => 197,
            "name" => "Russia",
            "currency" => "RUB",
            "phone" => 70,
            "code" => "RU",
            "number" => 643,
        ],
        [
            "id" => 198,
            "name" => "Saara Ocidental",
            "currency" => "MAD",
            "phone" => 212,
            "code" => "EH",
            "number" => 732,
        ],
        [
            "id" => 199,
            "name" => "Bonaire, Sint Eustatius and Saba",
            "currency" => "USD",
            "phone" => 599,
            "code" => "BQ",
            "number" => 535,
        ],
        [
            "id" => 200,
            "name" => "Samoa",
            "currency" => "WST",
            "phone" => 684,
            "code" => "WS",
            "number" => 882,
        ],
        [
            "id" => 201,
            "name" => "American Samoa",
            "currency" => "USD",
            "phone" => 1684,
            "code" => "AS",
            "number" => 16,
        ],
        [
            "id" => 202,
            "name" => "San Marino",
            "currency" => "EUR",
            "phone" => 378,
            "code" => "SM",
            "number" => 674,
        ],
        [
            "id" => 203,
            "name" => "Saint Helena, Ascension and Tristan da Cunha",
            "currency" => "SHP",
            "phone" => 290,
            "code" => "SH",
            "number" => 654,
        ],
        [
            "id" => 204,
            "name" => "Saint Lucia",
            "currency" => "XCD",
            "phone" => 1758,
            "code" => "LC",
            "number" => 662,
        ],
        [
            "id" => 205,
            "name" => "Saint Barthélemy",
            "currency" => "EUR",
            "phone" => 590,
            "code" => "BL",
            "number" => 652,
        ],
        [
            "id" => 206,
            "name" => "Saint Kitts and Nevis",
            "currency" => "XCD",
            "phone" => 1869,
            "code" => "KN",
            "number" => 659,
        ],
        [
            "id" => 207,
            "name" => "Sint Maarten (Dutch part)",
            "currency" => "ANG",
            "phone" => 1,
            "code" => "SX",
            "number" => 534,
        ],
        [
            "id" => 208,
            "name" => "Saint Pierre and Miquelon",
            "currency" => "EUR",
            "phone" => 508,
            "code" => "PM",
            "number" => 666,
        ],
        [
            "id" => 209,
            "name" => "São Tomé and Príncipe",
            "currency" => "STD",
            "phone" => 239,
            "code" => "ST",
            "number" => 678,
        ],
        [
            "id" => 210,
            "name" => "Saint Vincent and the Grenadines",
            "currency" => "XCD",
            "phone" => 1784,
            "code" => "VC",
            "number" => 670,
        ],
        [
            "id" => 211,
            "name" => "Senegal",
            "currency" => "XOF",
            "phone" => 221,
            "code" => "SN",
            "number" => 686,
        ],
        [
            "id" => 212,
            "name" => "Sierra Leone",
            "currency" => "SLL",
            "phone" => 232,
            "code" => "SL",
            "number" => 694,
        ],
        [
            "id" => 213,
            "name" => "Serbia",
            "currency" => "RSD",
            "phone" => 381,
            "code" => "RS",
            "number" => 688,
        ],
        [
            "id" => 215,
            "name" => "Seychelles",
            "currency" => "SCR",
            "phone" => 248,
            "code" => "SC",
            "number" => 690,
        ],
        [
            "id" => 216,
            "name" => "Syria",
            "currency" => "SYP",
            "phone" => 963,
            "code" => "SY",
            "number" => 760,
        ],
        [
            "id" => 217,
            "name" => "Somalia",
            "currency" => "SOS",
            "phone" => 252,
            "code" => "SO",
            "number" => 706,
        ],
        [
            "id" => 218,
            "name" => "Sri Lanka",
            "currency" => "LKR",
            "phone" => 94,
            "code" => "LK",
            "number" => 144,
        ],
        [
            "id" => 219,
            "name" => "Swaziland",
            "currency" => "SZL",
            "phone" => 268,
            "code" => "SZ",
            "number" => 748,
        ],
        [
            "id" => 220,
            "name" => "Sudan",
            "currency" => "SDG",
            "phone" => 249,
            "code" => "SD",
            "number" => 736,
        ],
        [
            "id" => 221,
            "name" => "South Sudan",
            "currency" => "SSP",
            "phone" => 211,
            "code" => "SS",
            "number" => 728,
        ],
        [
            "id" => 222,
            "name" => "Sweden",
            "currency" => "SEK",
            "phone" => 46,
            "code" => "SE",
            "number" => 752,
        ],
        [
            "id" => 223,
            "name" => "Switzerland",
            "currency" => "CHF",
            "phone" => 41,
            "code" => "CH",
            "number" => 756,
        ],
        [
            "id" => 224,
            "name" => "Suriname",
            "currency" => "SRD",
            "phone" => 597,
            "code" => "SR",
            "number" => 740,
        ],
        [
            "id" => 225,
            "name" => "Jan Mayen",
            "currency" => "NOK",
            "phone" => 47,
            "code" => "SJ",
            "number" => 744,
        ],
        [
            "id" => 226,
            "name" => "Thailand",
            "currency" => "THB",
            "phone" => 66,
            "code" => "TH",
            "number" => 764,
        ],
        [
            "id" => 227,
            "name" => "Taiwan",
            "currency" => "TWD",
            "phone" => 886,
            "code" => "TW",
            "number" => 158,
        ],
        [
            "id" => 228,
            "name" => "Tajikistan",
            "currency" => "TJS",
            "phone" => 992,
            "code" => "TJ",
            "number" => 762,
        ],
        [
            "id" => 229,
            "name" => "Tanzania",
            "currency" => "TZS",
            "phone" => 255,
            "code" => "TZ",
            "number" => 834,
        ],
        [
            "id" => 230,
            "name" => "French Southern and Antarctic Lands",
            "currency" => "EUR",
            "phone" => 262,
            "code" => "TF",
            "number" => 260,
        ],
        [
            "id" => 231,
            "name" => "British Indian Ocean Territory",
            "currency" => "USD",
            "phone" => 246,
            "code" => "IO",
            "number" => 86,
        ],
        [
            "id" => 232,
            "name" => "Palestinian Authority",
            "currency" => "ILS",
            "phone" => 970,
            "code" => "PS",
            "number" => 275,
        ],
        [
            "id" => 233,
            "name" => "Democratic Republic of Timor-Leste",
            "currency" => "USD",
            "phone" => 670,
            "code" => "TL",
            "number" => 626,
        ],
        [
            "id" => 234,
            "name" => "Togo",
            "currency" => "XOF",
            "phone" => 228,
            "code" => "TG",
            "number" => 768,
        ],
        [
            "id" => 235,
            "name" => "Tonga",
            "currency" => "TOP",
            "phone" => 676,
            "code" => "TO",
            "number" => 776,
        ],
        [
            "id" => 236,
            "name" => "Tokelau",
            "currency" => "NZD",
            "phone" => 690,
            "code" => "TK",
            "number" => 772,
        ],
        [
            "id" => 237,
            "name" => "Trinidad and Tobago",
            "currency" => "TTD",
            "phone" => 1868,
            "code" => "TT",
            "number" => 780,
        ],
        [
            "id" => 238,
            "name" => "Tunisia",
            "currency" => "TND",
            "phone" => 216,
            "code" => "TN",
            "number" => 788,
        ],
        [
            "id" => 239,
            "name" => "Turkmenistan",
            "currency" => "TMT",
            "phone" => 7370,
            "code" => "TM",
            "number" => 795,
        ],
        [
            "id" => 240,
            "name" => "Turkey",
            "currency" => "TRY",
            "phone" => 90,
            "code" => "TR",
            "number" => 792,
        ],
        [
            "id" => 241,
            "name" => "Tuvalu",
            "currency" => "AUD",
            "phone" => 688,
            "code" => "TV",
            "number" => 798,
        ],
        [
            "id" => 242,
            "name" => "Ukraine",
            "currency" => "UAH",
            "phone" => 380,
            "code" => "UA",
            "number" => 804,
        ],
        [
            "id" => 243,
            "name" => "Uganda",
            "currency" => "UGX",
            "phone" => 256,
            "code" => "UG",
            "number" => 800,
        ],
        [
            "id" => 244,
            "name" => "Uruguay",
            "currency" => "UYU",
            "phone" => 598,
            "code" => "UY",
            "number" => 858,
        ],
        [
            "id" => 245,
            "name" => "Uzbekistan",
            "currency" => "UZS",
            "phone" => 998,
            "code" => "UZ",
            "number" => 860,
        ],
        [
            "id" => 246,
            "name" => "Vanuatu",
            "currency" => "VUV",
            "phone" => 678,
            "code" => "VU",
            "number" => 548,
        ],
        [
            "id" => 247,
            "name" => "Vatican City",
            "currency" => "EUR",
            "phone" => 39,
            "code" => "VA",
            "number" => 336,
        ],
        [
            "id" => 248,
            "name" => "Bolivarian Republic of Venezuela",
            "currency" => "VEF",
            "phone" => 58,
            "code" => "VE",
            "number" => 862,
        ],
        [
            "id" => 249,
            "name" => "Vietnam",
            "currency" => "VND",
            "phone" => 84,
            "code" => "VN",
            "number" => 704,
        ],
        [
            "id" => 250,
            "name" => "Wallis and Futuna",
            "currency" => "XPF",
            "phone" => 681,
            "code" => "WF",
            "number" => 876,
        ],
        [
            "id" => 251,
            "name" => "Zambia",
            "currency" => "ZMW",
            "phone" => 260,
            "code" => "ZM",
            "number" => 894,
        ],
        [
            "id" => 252,
            "name" => "Zimbabwe",
            "currency" => "ZWL",
            "phone" => 263,
            "code" => "ZW",
            "number" => 716,
        ],
    ];

    public function addresses()
    {
        return $this->hasMany(Address::class);
    }

    public function customers()
    {
        return $this->hasMany(Customer::class);
    }
}
